image: "rust:latest"

test:cargo:
  script:
    - rustc --version && cargo --version # Print version info for debugging
    - cargo test --workspace --verbose
    - rustup components add clippy
    - cargo clippy --all
